### ISSUE TITLE
1.15.2 Strange Behavior For Tubes At Large

### ISSUE THREAD

**Issue by VaelophisNyx** [Commoble/tubesreloaded#11]
Filters that are adjacent and facing side-to-side will output into each other (likely due to the new GUI), causing the item filtered to immediately spill out onto the floor.

In addition they just seem to spit any item of a matching or not matching filtered type out instantly no matter what orientation they are in.

**Comment by VaelophisNyx** [comment]
I'm actually just getting some seriously weird behavior from tubes. they will not count anything as a valid destination, other than a Botania Chute; or an invalid filter, or a *valid* filter all of which will instantly spit it out regardless of orientation.

**Comment by Commoble** [comment]
I haven't been able to reproduce this, can you provide additional context? The modpack you're using and a screenshot of the arrangement of your blocks would be most helpful

**Comment by Commoble** [comment]
Closing as it's been over a year with no further information
