### ISSUE TITLE
Crash: Null Pointer Exception in TubeTileEntity

### ISSUE THREAD

**Issue by Vaelzan** [Commoble/tubesreloaded#2]
In the 'getCapability' function, 'side' is nullable, but the function body doesn't perform a null check, leading to a crash if getCapability is called without the 'side' parameter being present and 'cap' is ITEM_HANDLER_CAPABILITY.

https://github.com/Commoble/tubesreloaded/blob/def86f588ee8e0aeb12f3bc3ed16d8b1816f3a4a/src/main/java/com/github/commoble/tubesreloaded/common/blocks/tube/TubeTileEntity.java#L227

**Comment by Commoble** [comment]
Fixed in 1.14.4-1.1.0c, thank you for finding this!
