### ISSUE TITLE
Using the mod is crashing 1.19.0 version worlds

### ISSUE THREAD

**Issue by GuhDiaz** [Commoble/tubesreloaded#21]
Using the mod is crashing 1.19.0 version worlds

When I place some object from the mod, it crashes immediately and disconnects!

I really like this mod, I would like to use it again

Pls, help!!

**Comment by Commoble** [comment]
Hello! Please upload the crash log and latest.log on gist or pastebin or paste.gemwire.uk or a similar website and post the links here and I'll see if I can determine why it's crashing and how to make it not crash

**Comment by GuhDiaz** [comment]
https://pastebin.com/WR4qPN5B

If you need my friends' are also crashing

**Comment by Commoble** [comment]
Do you get the crash when you don't use optifine or tlauncher?

**Comment by GuhDiaz** [comment]
That's right, without optfine it works normally, tnks
