### ISSUE TITLE
[suggestion] add 'pipe' keyword to curseforge description

### ISSUE THREAD

**Issue by n0proxy** [Commoble/tubesreloaded#23]
I was desperately searching for a simple 1.19.2 Forge pipe mod that suited my needs last week, trying every keyword I could think of - pipe, transport (not sure why this one didnt work), filter, move, conveyor... There was nothing I liked! 

I had given up actually, until I happened to see this mod while searching for something else with 'reloaded' in the name. I highly recommend lengthening the preview description of the mod on curseforge with a few of those keywords so it can be found by other people like me!

**Comment by Commoble** [comment]
It's tagged with the "Energy, Fluid, and Item Transportation" category, you can search for 1.19.2 mods in this category using curseforge's (admittedly generally bad) search features

https://www.curseforge.com/minecraft/mc-mods/technology/technology-item-fluid-energy-transport?filter-game-version=2020709689%3A9366&filter-sort=4
