### ISSUE TITLE
Items not move through tubs

### ISSUE THREAD

**Issue by Howman** [Commoble/tubesreloaded#3]
in version tubesreloaded-1.14.4-1.1.0c the hopper will remove item from chest but will not move through the tube item is dropped besides chest.

**Comment by Commoble** [comment]
Can I see a picture of your setup?

**Comment by Howman** [comment]
Will a short 2 min mp4 do. it was 145 meg i used vlc player to compress to 11 meg ziped

[Minecraft 1.14.4 2019-11-07 22-54-35.zip](https://github.com/Commoble/tubesreloaded/files/3822976/Minecraft.1.14.4.2019-11-07.22-54-35.zip)

Playing with your mod I found out that you need to have a chest on end of tub for it to work I thought it would just spit out of tube but in the video it still does not work hopefully you can figure out what i have done wrong ( poor quality video )

**Comment by Commoble** [comment]
I see that your line of tubes is very long. There is a configurable limit on how long tubes can be; by default, tubes don't work very well when you have more than 100 tubes connected to each other, and they don't work at all when you have more than 200 tubes connected to each other. There are two ways around this:

1) Increase the limits in the server config
2) Use shunts or hoppers every 100 tubes or so to break up your long line of tubes into several smaller lines of tubes (recommended)

**Comment by Commoble** [comment]
Also I just noticed that the configurable cap was being ignored in at least one place (it was using the default cap regardless of the config), so I'll put a fix up for that soon

**Comment by Howman** [comment]
Ok thank you
