### ISSUE TITLE
Crash when placing Osmosis filter to pull from MineColonies hutBlock

### ISSUE THREAD

**Issue by Nachtflame** [Commoble/tubesreloaded#4]
As per title - Continual crash of client to desktop on world load (have not attempted on dedicated server)

tubesreloaded-1.14.4-1.1.1b
minecolonies-0.10.561 up to .586
forge-28.1.96 up to .104

[crash-2019-12-11_10.02.52-server.txt](https://github.com/Commoble/tubesreloaded/files/3951891/crash-2019-12-11_10.02.52-server.txt)

**Comment by Commoble** [comment]
Looks like there's an infinite loop going back and forth between the two blocks, it doesn't look like a difficult fix so I'll get a patch up today or tomorrow

**Comment by Commoble** [comment]
Fixed in 1.14.4-1.1.1c https://www.curseforge.com/minecraft/mc-mods/tubes-reloaded/files/2841763

**Comment by Raulweg** [comment]
Hey! Im in Minecraft 1.16.2 with this mod, it is crashing everytime when i try to transport a item into a chest

**Comment by Commoble** [comment]
> Hey! Im in Minecraft 1.16.2 with this mod, it is crashing everytime when i try to transport a item into a chest

Open a new issue with more details + crash report and latest.log
