### ISSUE TITLE
Advanced filtering improvement

### ISSUE THREAD

**Issue by MrGuitou** [Commoble/tubesreloaded#9]
Hello.

Would it be possible to improve the filter system?

For example:

- Filter by the material of the object, rather than by the object itself.
Practical case: filter containing an iron ingot, filtering any iron object (sword, torso, block, etc ...)

- Filter by type of object.
Practical case: filter containing a wooden sword, filtering any sword, whatever the material (iron, gold, diamond, etc ...

- Filter by magic.
Practical case: Filter containing an enchanted book, filtering any object having the corresponding enchantment.
Why not with a switch to check the level of enchantment.

I hope this proposal will interest you.
Keep up the great work.

Cordially.

**Comment by Kthargas** [comment]
In my opinion, it would be enough to just increase the slot number from 1 to 5 or something like this.
